book-molal начальная разметка
Serhii-Ivasiuk/book-js-team-project pull request #15
Opened 2023-04-12 21:58 UTC by VladimirMV

2023-04-13 09:04 UTC, Serhii-Ivasiuk requested changes

2023-04-13 09:04 UTC, Serhii-Ivasiuk commented on src/sass/components/_pop-up.scss
> +  font-family: 'DM Sans';
шрифт по замовчуванюю встановлений на body, не варто його явно задавати

2023-04-13 09:04 UTC, Serhii-Ivasiuk commented on src/sass/components/_pop-up.scss
> +  font-style: normal;
те саме, це по замовчуванюю є.

2023-04-13 09:04 UTC, Serhii-Ivasiuk commented on src/sass/components/_pop-up.scss
> +  box-sizing: border-box;
це теж є по-замовчуванню, треба прибрати.
загалом, дуже багато зайвих стилів - потрібно добре рефакторити

2023-04-13 09:04 UTC, Serhii-Ivasiuk commented on src/partials/pop-up.html
> +          <h2 class="book-name">HELLO BEAUTIFUL</h2>
В розмітці не має бути UPPERCASE, це прописується стилями

2023-04-13 13:48 UTC, VladimirMV commented on src/partials/pop-up.html
> +<html>
Убрал.

2023-04-13 13:51 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +  font-size: 16px;
Убрал

2023-04-13 13:51 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +  line-height: 18px;
Добавил калк

2023-04-13 13:51 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +  font-family: $font-dm-sans;
Убрал

2023-04-13 13:53 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +.icon,
Убрал

2023-04-13 13:53 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +  font-family: 'DM Sans';
Убрал

2023-04-13 13:53 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +  font-style: normal;
Убрал

2023-04-13 13:54 UTC, VladimirMV commented on src/partials/pop-up.html
> +          <h2 class="book-name">HELLO BEAUTIFUL</h2>
Добавил

2023-04-13 14:52 UTC, VladimirMV commented on src/sass/components/_pop-up.scss
> +      border: 3px solid rgba(79, 46, 232, 1)
Што то туплю с изменением цвета иконки. Fill не работает. Помню, что есть нюанс, но не помню где.

2023-04-15 00:37 UTC, Serhii-Ivasiuk approved these changes

2023-04-15 00:37 UTC, merged